logging.level.root=ERROR
spring.datasource.url=jdbc:postgresql://ecobites-db-container:5432/ecobitesdb
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true

logging.level.com.epam.ecobites.aspect=DEBUG
logging.level.org.flywaydb=DEBUG

springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/api-docs