CREATE TABLE ECO_USER(
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(255) UNIQUE NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,  -- this should still be hashed
    IMAGE TEXT
);

CREATE TABLE RECIPE(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE NOT NULL,
    TIME INT NOT NULL,
    SUMMARY TEXT NOT NULL,
    IMAGE TEXT
);

CREATE TABLE INGREDIENT(
    ID SERIAL PRIMARY KEY,
    NAME UNIQUE VARCHAR(255) NOT NULL
);

CREATE TABLE INGREDIENT_DETAIL(
    ID SERIAL PRIMARY KEY,
    QUANTITY SMALLINT NOT NULL,
    UNIT VARCHAR(100) NOT NULL
);

CREATE TABLE RECIPE_INGREDIENT(
    ID SERIAL PRIMARY KEY,
    RECIPE_ID INT NOT NULL,
    INGREDIENT_ID INT NOT NULL,
    INGREDIENT_DETAIL_ID INT NOT NULL
);

CREATE TABLE REVIEW(
    ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL,
    RECIPE_ID INT NOT NULL,
    RATE INT CHECK (RATE >= 1 AND RATE <= 5),
    CONTENT TEXT
);

CREATE TABLE SHOPPING_LIST_ITEM(
    ID SERIAL PRIMARY KEY,
    RECIPE_INGREDIENT_ID INT NOT NULL,
    USER_ID INT NOT NULL
);