CREATE TABLE ECO_USER (
    ID SERIAL PRIMARY KEY,
    Username VARCHAR NOT NULL UNIQUE,
    Email VARCHAR NOT NULL UNIQUE,
    Password VARCHAR NOT NULL,
    Image VARCHAR,
    Date_Created TIMESTAMP NOT NULL
);

CREATE TABLE RECIPE (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR NOT NULL,
    Time INT NOT NULL,
    Summary TEXT NOT NULL,
    Image VARCHAR
);

CREATE TABLE INGREDIENT (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE REVIEW (
    ID SERIAL PRIMARY KEY,
    UserID INT NOT NULL,
    RecipeID INT NOT NULL,
    Rate INT,
    Content TEXT,
    Date_Created TIMESTAMP NOT NULL
);

CREATE TABLE RECIPE_INGREDIENT (
    ID SERIAL PRIMARY KEY,
    RecipeID INT NOT NULL,
    IngredientID INT NOT NULL,
    IngredientDetailID INT NOT NULL
);

CREATE TABLE INGREDIENT_DETAIL (
    ID SERIAL PRIMARY KEY,
    Quantity INT NOT NULL,
    Unit VARCHAR NOT NULL
);

CREATE TABLE SHOPPING_ITEM (
    ID SERIAL PRIMARY KEY,
    IngredientID INT NOT NULL,
    RecipeID INT NOT NULL,
    UserID INT NOT NULL
);

CREATE TABLE SHOPPING_ITEM_DETAIL (
    ID SERIAL PRIMARY KEY,
    ShoppingItemID INT NOT NULL,
    Quantity INT NOT NULL,
    Unit VARCHAR NOT NULL
);

CREATE TABLE RECIPE_STEP (
    ID SERIAL PRIMARY KEY,
    RecipeID INT NOT NULL,
    Number SMALLINT NOT NULL,
    Title VARCHAR NOT NULL,
    Description TEXT NOT NULL,
    Image TEXT
);